# Generated by Django 4.2.2 on 2023-06-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1995-02-05'),
            preserve_default=False,
        ),
    ]
